In [3]:
!pip install yfinance
!pip install yahoo_fin

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.85-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Collecting requests>=2.26
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.4 MB/s
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.9.1)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Installing collected packages: requests, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
Successfully installed requests-2.28.1 yfinance-0.1.85
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yahoo_fin
  Downloading yahoo_fin-0.8.9.1-py3-none-any.whl (10 kB)
Collecting feedparser
  Downloading feedparser-6.0.10-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 4.0 MB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from yahoo_fin) (1.3.5)
Collecting requests-html
  Downloading requests_html-0.10.0-py3-none-any.whl (13 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from yahoo_fin) (2.28.1)
Collecting sgmllib3k
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (2022.6)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->yahoo_fin) (1.15.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2.10)
Collecting parse
  Downloading parse-1.19.0.tar.gz (30 kB)
Collecting pyppeteer>=0.0.14
  Downloading pyppeteer-1.0.2-py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 2.0 MB/s
Collecting pyquery
  Downloading pyquery-1.4.3-py3-none-any.whl (22 kB)
Collecting fake-useragent
  Downloading fake_useragent-0.1.14-py3-none-any.whl (13 kB)
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (from requests-html->yahoo_fin) (0.0.1)
Collecting w3lib
  Downloading w3lib-2.0.1-py3-none-any.whl (20 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 46.1 MB/s
Collecting pyee<9.0.0,>=8.1.0
  Downloading pyee-8.2.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.13.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (1.4.4)
Collecting websockets<11.0,>=10.0
  Downloading websockets-10.4-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (106 kB)
     |████████████████████████████████| 106 kB 57.6 MB/s
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.64.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.10.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4->requests-html->yahoo_fin) (4.6.3)
Collecting cssselect>0.7.9
  Downloading cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests-html->yahoo_fin) (4.9.1)
Building wheels for collected packages: parse, sgmllib3k
  Building wheel for parse (setup.py) ... done
  Created wheel for parse: filename=parse-1.19.0-py3-none-any.whl size=24590 sha256=63ce275226c6d40c8dfdc1f0648e5a15feeb059c1647c5565605091b1d0d23ca
  Stored in directory: /root/.cache/pip/wheels/9c/aa/cc/f2228050ccb40f22144b073f15a2c84f11204f29fc0dce028e
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6065 sha256=cfb82a8a56d80bc3aa418e1e03438146f2b63aee35dd4b48e7e7db8f1e751186
  Stored in directory: /root/.cache/pip/wheels/73/ad/a4/0dff4a6ef231fc0dfa12ffbac2a36cebfdddfe059f50e019aa
Successfully built parse sgmllib3k
Installing collected packages: websockets, urllib3, pyee, cssselect, w3lib, sgmllib3k, pyquery, pyppeteer, parse, fake-useragent, requests-html, feedparser, yahoo-fin
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
Successfully installed cssselect-1.2.0 fake-useragent-0.1.14 feedparser-6.0.10 parse-1.19.0 pyee-8.2.2 pyppeteer-1.0.2 pyquery-1.4.3 requests-html-0.10.0 sgmllib3k-1.0.0 urllib3-1.26.12 w3lib-2.0.1 websockets-10.4 yahoo-fin-0.8.9.1

In [4]:
#### stock_info methods:

#get_analysts_info()
#get_balance_sheet()
#get_cash_flow()
#get_data()
#get_day_gainers()        # UNUSABLE WITHOUT requests_html
#get_day_losers()         # UNUSABLE WITHOUT requests_html
#get_day_most_active()    # UNUSABLE WITHOUT requests_html
#get_holders()
#get_income_statement()
#get_live_price()
#get_quote_table()
#get_top_crypto()         # UNUSABLE WITHOUT requests_html
#get_stats()
#get_stats_valuation()
#tickers_dow()
#tickers_nasdaq()
#tickers_other()
#tickers_sp500()
#get_calls()
#get_expiration_dates()    # UNUSABLE WITHOUT requests_html
#get_options_chain()
#get_puts()

In [5]:
from yahoo_fin.stock_info import get_data

# get_data(ticker, start_date = None, end_date = None, index_as_date = True, interval = “1d”)

amazon_weekly= get_data("amzn", start_date="12/04/2009", end_date="12/04/2021", index_as_date = True, interval="1wk")
amazon_weekly

,open,high,low,close,adjclose,volume,ticker
2009-11-30,7.181000,7.295500,6.755500,6.879000,6.879000,627018000,AMZN
2009-12-07,6.900000,6.950000,6.491000,6.707500,6.707500,957260000,AMZN
2009-12-14,6.625000,6.630500,6.282500,6.424000,6.424000,915898000,AMZN
2009-12-21,6.524000,6.985000,6.509500,6.923500,6.923500,648120000,AMZN
2009-12-28,6.987500,7.129000,6.726000,6.726000,6.726000,572014000,AMZN
...,...,...,...,...,...,...,...
2021-11-01,168.089996,178.312500,164.177505,175.949493,175.949493,399674000,AMZN
2021-11-08,176.162003,180.272507,172.352493,176.257507,176.257507,327002000,AMZN
2021-11-15,176.850006,188.107498,176.257507,183.828506,183.828506,366946000,AMZN
2021-11-22,183.819000,185.673004,175.207504,175.227997,175.227997,277034000,AMZN
2021-11-29,177.382004,179.800003,166.929993,169.489502,169.489502,365688000,AMZN

In [6]:
ticker_list = ["amzn", "aapl", "ba"]

historical_datas = {}
for ticker in ticker_list:
    historical_datas[ticker] = get_data(ticker)

In [7]:
historical_datas["aapl"]

,open,high,low,close,adjclose,volume,ticker
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.099874,469033600,AAPL
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.094663,175884800,AAPL
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.087715,105728000,AAPL
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089886,86441600,AAPL
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092492,73449600,AAPL
...,...,...,...,...,...,...,...
2022-11-07,137.110001,139.149994,135.669998,138.919998,138.919998,83374600,AAPL
2022-11-08,140.410004,141.429993,137.490005,139.500000,139.500000,89908500,AAPL
2022-11-09,138.500000,138.550003,134.589996,134.869995,134.869995,74917800,AAPL
2022-11-10,141.240005,146.869995,139.500000,146.869995,146.869995,118854000,AAPL
2022-11-11,145.820007,150.009995,144.369995,149.699997,149.699997,93903800,AAPL